#!/bin/bash

# 修复文件名格式的脚本
fix_filename() {
  dir=$1
  old_name=$2
  new_name=$3
  
  if [ -f "$dir/$old_name" ]; then
    mv "$dir/$old_name" "$dir/$new_name"
    echo "已修改: $old_name -> $new_name"
  else
    echo "文件不存在: $dir/$old_name"
  fi
}

# 修复纯中文文件名
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/loki.imageset" "洛基.png" "loki.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/jung.imageset" "荣格.png" "jung.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/kant.imageset" "康德.png" "kant.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/kawabata.imageset" "川端康成.png" "kawabata.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/laozi.imageset" "老子.png" "laozi.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/luxun.imageset" "鲁迅.png" "luxun.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/marie_curie.imageset" "居里夫人.png" "marie_curie.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/marquez.imageset" "马尔克斯.png" "marquez.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/picasso.imageset" "毕加索.png" "picasso.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/sanmao.imageset" "三毛.png" "sanmao.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/tolstoy.imageset" "托尔斯泰.png" "tolstoy.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/van_gogh.imageset" "梵高.png" "van_gogh.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/zeus.imageset" "宙斯.png" "zeus.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/zhuangzi.imageset" "庄子.png" "zhuangzi.png"

# 修复带下划线注释的文件名
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/caesar.imageset" "caesar _ 凯撒.png" "caesar.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/chang_e.imageset" "chang_e _ 嫦娥.png" "chang_e.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/chihiro.imageset" "chihiro _ 千寻.png" "chihiro.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/cixi.imageset" "cixi _ 慈禧.png" "cixi.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/cleopatra.imageset" "cleopatra _ 克莱奥帕特拉.png" "cleopatra.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/cloud_strife.imageset" "cloud_strife _ 克劳德.png" "cloud_strife.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/conan.imageset" "conan _ 柯南.png" "conan.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/diaochan.imageset" "diaochan _ 貂蝉.png" "diaochan.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/edward_elric.imageset" "edward_elric _ 爱德华·艾尔利克.png" "edward_elric.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/eleven.imageset" "eleven _ 十一.png" "eleven.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/ellie.imageset" "ellie _ 艾莉.png" "ellie.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/eren.imageset" "eren _ 艾伦.png" "eren.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/ethan_hunt.imageset" "ethan_hunt _ 伊森·亨特.png" "ethan_hunt.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/ezio_auditore.imageset" "ezio_auditore _ 艾吉奥.png" "ezio_auditore.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/forrest_gump.imageset" "forrest_gump _ 阿甘.png" "forrest_gump.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/ganesha.imageset" "ganesha _ 象头神.png" "ganesha.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/genghis.imageset" "genghis _ 成吉思汗.png" "genghis.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/genshin_traveler.imageset" "genshin_traveler _ 原神旅行者.png" "genshin_traveler.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/goku.imageset" "goku _ 孙悟空(动漫) .png" "goku.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/hanwudi.imageset" "hanwudi _ 汉武帝.png" "hanwudi.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/harry_potter.imageset" "harry_potter _ 哈利·波特.png" "harry_potter.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/hatsune_miku.imageset" "hatsune _ 初音_副本.png" "hatsune_miku.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/hou_yi.imageset" "hou_yi _ 后羿.png" "hou_yi.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/inuyasha.imageset" "inuyasha _ 犬夜叉.png" "inuyasha.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/ip_man.imageset" "ip_man _ 叶问.png" "ip_man.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/jack_sparrow.imageset" "jack_sparrow _ 杰克·斯派洛.png" "jack_sparrow.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/jingke.imageset" "jingke _ 荆轲.png" "jingke.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/jinx.imageset" "jinx _ 金克斯.png" "jinx.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/joan_of_arc.imageset" "joan_of_arc _ 圣女贞德.png" "joan_of_arc.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/kangxi.imageset" "kangxi _ 康熙.png" "kangxi.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/kirby.imageset" "kirby _ 卡比.png" "kirby.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/kratos.imageset" "kratos _ 奎托斯.png" "kratos.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/lelouch.imageset" "lelouch _ 鲁路修.png" "lelouch.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/levi.imageset" "levi _ 利威尔.png" "levi.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/light_yagami.imageset" "light_yagami _ 夜神月.png" "light_yagami.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/luffy.imageset" "luffy _ 路飞.png" "luffy.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/mario.imageset" "mario _ 马里奥.png" "mario.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/master_chief.imageset" "master_chief _ 士官长.png" "master_chief.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/maximus.imageset" "maximus _ 马克西姆斯.png" "maximus.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/michael_scott.imageset" "michael_scott _ 迈克尔·斯科特.png" "michael_scott.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/monet.imageset" "monet _ 莫奈.png" "monet.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/nezuko.imageset" "nezuko _ 祢豆子.png" "nezuko.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/nightingale.imageset" "nightingale _ 南丁格尔.png" "nightingale.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/osiris.imageset" "osiris _ 奥西里斯.png" "osiris.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/pikachu.imageset" "pikachu _ 皮卡丘.png" "pikachu.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/qinshihuang.imageset" "qinshihuang _ 秦始皇.png" "qinshihuang.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/quetzalcoatl.imageset" "quetzalcoatl _ 羽蛇神.png" "quetzalcoatl.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/raymond_reddington.imageset" "raymond_reddington _ 雷蒙德·雷丁顿.png" "raymond_reddington.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/saber.imageset" "saber _ 阿尔托莉雅.png" "saber.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/sailor_moon.imageset" "sailor_moon _ 美少女战士.png" "sailor_moon.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/saitama.imageset" "saitama _ 埼玉.png" "saitama.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/saul_goodman.imageset" "saul_goodman _ 索尔·古德曼.png" "saul_goodman.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/sheldon_cooper.imageset" "sheldon_cooper _ 谢尔顿·库珀.png" "sheldon_cooper.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/sherlock_bbc.imageset" "sherlock_bbc _ BBC版夏洛克.png" "sherlock_bbc.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/solid_snake.imageset" "solid_snake _ 固蛇.png" "solid_snake.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/spike_spiegel.imageset" "spike_spiegel _ 斯派克·斯皮格尔 .png" "spike_spiegel.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/tanjiro.imageset" "tanjiro _ 炭治郎.png" "tanjiro.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/thomas_shelby.imageset" "thomas_shelby _ 托马斯·谢尔比.png" "thomas_shelby.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/thor.imageset" "thor _ 雷神托尔.png" "thor.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/totoro.imageset" "totoro _ 龙猫 .png" "totoro.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/tyrion_lannister.imageset" "tyrion_lannister _ 提利昂·兰尼斯特.png" "tyrion_lannister.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/walter_white.imageset" "walter_white _ 沃尔特·怀特.png" "walter_white.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/wangzhaojun.imageset" "wangzhaojun _ 王昭君.png" "wangzhaojun.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/xishi.imageset" "xishi _ 西施.png" "xishi.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/zhangdaqian.imageset" "zhangdaqian _ 张大千.png" "zhangdaqian.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/zhen_huan.imageset" "zhen_huan _ 甄嬛.png" "zhen_huan.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/zhongli.imageset" "zhongli _ 钟离.png" "zhongli.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/2b.imageset" "2b _ 2B.png" "2b.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/agent_47.imageset" "agent_47 _ 47号特工.png" "agent_47.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/alexander.imageset" "alexander _ 亚历山大.png" "alexander.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/aloy.imageset" "aloy _ 艾洛伊.png" "aloy.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/amelie.imageset" "amelie _ 艾米丽.png" "amelie.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/athena.imageset" "athena _ 雅典娜.png" "athena.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/darth_vader.imageset" "darth_vader _ 达斯·维德.png" "darth_vader.png"
fix_filename "虫遇/Assets.xcassets/HistoricalFigures/female_ninja.imageset" "female_ninja _ 女忍者.png" "female_ninja.png"
