#!/bin/bash

echo "=========================================="
echo "Sandbox 环境测试准备检查"
echo "=========================================="
echo ""

echo "📋 测试前准备清单："
echo ""
echo "1. ✅ 创建 Sandbox 测试账号"
echo "   - 登录 App Store Connect"
echo "   - 用户和访问 → 沙盒技术测试员 → 添加测试账号"
echo "   - 记录账号信息（邮箱和密码）"
echo ""
echo "2. ✅ 准备真机设备"
echo "   - 使用 iPhone 或 iPad（不是模拟器）"
echo "   - 确保设备可以安装应用"
echo ""
echo "3. ✅ 退出设备上的 Apple ID"
echo "   - 设置 → Apple ID → 退出登录"
echo "   - 或在购买时选择'使用其他账号'"
echo ""
echo "4. ✅ 安装应用"
echo "   - 通过 Xcode 安装到真机"
echo "   - 或使用 TestFlight 安装"
echo ""
echo "=========================================="
echo "测试步骤"
echo "=========================================="
echo ""
echo "1. 打开应用 → 充值页面"
echo "2. 点击购买按钮"
echo "3. 弹出登录时，输入 Sandbox 测试账号"
echo "4. 完成购买流程"
echo "5. 购买完成后，告诉我，我会检查验证结果"
echo ""
echo "=========================================="
echo "提示"
echo "=========================================="
echo ""
echo "⚠️  Sandbox 不会扣费（测试环境）"
echo "⚠️  必须使用真机（模拟器无法生成真实的 JWT receipt）"
echo "⚠️  购买时不要使用你的真实 Apple ID"
echo ""
echo "准备好后，执行购买，然后告诉我完成，我会检查结果！"

